/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'magneto' at '17-6-23 下午5:09' with Gradle 2.12
 *
 * @author magneto, @date 17-6-23 下午5:09
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        System.out.println("hello world!");
    }
}
